### PR TITLE
Fix ConnectParams for vddk 6.7.0

### LINKED ISSUE #19: ConnectParams should be using the 6_5_0 struct on >= 6.5.0?
The ConnectParams are setup with a hardocded value of 6.5.0 in order to add an extra field on that version.  However, 6.7.0 is not using that extended version.  Should it?  If so, is this a bug?

### PR DESCRIPTION
**Pull request by agrare**
Handle vddk versions >= 6.5.0

Fixes #19

### CODE REVIEW

File: spec/ffi-vix_disk_lib/api_spec.rb [hunk 1]
```diff
@@ -22,15 +22,8 @@
   end
 
   describe "ConnectParams" do
-    case described_class::VERSION
```
Comment (agrare) [inline spec/ffi-vix_disk_lib/api_spec.rb]: Since we're testing with the stub library now this case didn't make sense, but if you change the Makefile to build e.g. 5.5.0 it picks up the correct ConnectParams:

```
  4) FFI::VixDiskLib::API ConnectParams has vimApiVer
     Failure/Error: expect(described_class::ConnectParams.members).to include(:vimApiVer)
     
       expected [:vmxSpec, :serverName, :thumbPrint, :privateUse, :credType, :creds, :port] to include :vimApiVer
       Diff:
       @@ -1,2 +1,2 @@
       -[:vimApiVer]
       +[:vmxSpec, :serverName, :thumbPrint, :privateUse, :credType, :creds, :port]
```

Not sure if there's a way to test multiple .so versions in the same spec

Comment (Fryguy) [reply spec/ffi-vix_disk_lib/api_spec.rb]: We can structure the travis.yml to do multiple builds based on some env car, then use that env car to build the library, maybe?

Comment (agrare) [reply spec/ffi-vix_disk_lib/api_spec.rb]: Yeah I can do that, I'll update the Makefile to pull the vddk version from an env var

Comment (Fryguy) [reply spec/ffi-vix_disk_lib/api_spec.rb]: And default to 6.7.0 or something
